### ISSUE TITLE
Get Market Value

### ISSUE THREAD

**Issue by Giswald** [FatherFoxxy/CSharpTradeOffers#10]
Maybe use one of this API?
https://www.reddit.com/r/SteamBot/comments/3piuxx/steamlyticscsgo_an_alternative_to_steamanalyst/
https://github.com/andrewda/CSGOItemDB.com
http://csgo.steamlytics.xyz/

https://bitskins.com/

**Comment by FatherFoxxy** [comment]
The plan is interact with Steam itself and no outside sources, sorry.
