### ISSUE TITLE
Mobile Authenticator

### ISSUE THREAD

**Issue by BitPhinix** [FatherFoxxy/CSharpTradeOffers#12]
Can´t trade! There is no Mobile Authenticator implementation! Please Add.

**Comment by FatherFoxxy** [comment]
2FA is supported, but Escrow bypasses are not. Are you referring to the trade escrow?

**Comment by FatherFoxxy** [comment]
Yes, you are referring to escrow, never mind. I'm working on implementing https://github.com/geel9/SteamAuth
