### ISSUE TITLE
Webexception was unhandled

### ISSUE THREAD

**Issue by Hitch** [FatherFoxxy/CSharpTradeOffers#13]
after i login and the program logs me in successfully after i give the two factors code , and starts pulling offers every 10 seconds , i have pending offers already , but the program crashed giving me , webexception was unhandled , i've tried to debug it ... ive tried to see the error and it appears that the server is responding with 500 error ... 
so if you can help :)

**Comment by FatherFoxxy** [comment]
Does this happen the minute it attempts to receive an offer or after a few times?

**Comment by Hitch** [comment]
no the minute it starts to pull the offer

**Comment by Hitch** [comment]
but it doesn't happen when there's no pending offers the last time i checked

**Comment by FatherFoxxy** [comment]
The fact that it has the 2FA code makes me think that you have mobile confirmations enabled, is this correct?

**Comment by Hitch** [comment]
yup its enabled

**Comment by FatherFoxxy** [comment]
Unfortunately, I have not done much testing in that area. Because of this, I have not finished adding support for mobile confirmations. Sorry!

**Comment by Hitch** [comment]
its okai , no problem , but can we talk in private  i need your help in some stuff cuz im creating my own bot right now , so i might use some of your experience
