### ISSUE TITLE
Error while creating a new SteamChatHandler

### ISSUE THREAD

**Issue by BitPhinix** [FatherFoxxy/CSharpTradeOffers#15]
CSharpTradeOffers.Community.ChatException: Error fetching access token, the account specified is not authorized to use this feature.

I have no idear why! My Account isnt resticted and my api key is valid. The program works with my main account but I dont want to run it there.

Please help! 

BitPhinix

**Comment by FatherFoxxy** [comment]
If you know how to use Fiddler to fetch web requests, run the bot with the SteamChatHandler and show me the web page that this function accesses: https://github.com/FatherFoxxy/CSharpTradeOffers/blob/master/CSharpTradeOffers/Community/SteamChatHandler.cs#L97

This will tell me if your account isn't authorized or not.

**Comment by BitPhinix** [comment]
I have no idear why but i really have no permissions to usw the Steam chat in my Browser ! I have contakted the Steam support. THX for helping.
