### ISSUE TITLE
GetMarketHashName not working

### ISSUE THREAD

**Issue by bruxo00** [FatherFoxxy/CSharpTradeOffers#19]
Hey! I'm using your library and it is awesome, but, I can't make the function **GetMarketHashName** working because it throws an error on **SteamEconomyHandler** on **GetClassInfo **in the return (line 58 of SteamEconomyHandler.cs):

`An unhandled exception of type 'System.InvalidOperationException' occurred in System.Core.dll`
`Additional Information: The sequence contains no elements`

What can I do to solve this? Already tried with other account and nothing. Thanks ;)

**Comment by FatherFoxxy** [comment]
I don't work on this library anymore. If you want, debug it and then commit to the repository. Sorry.

**Comment by bruxo00** [comment]
Oh :(

This is such a good library, what a shame that it will be abandonned :(

**Comment by FatherFoxxy** [comment]
Quick note, I probably fixed it.
