### ISSUE TITLE
Parsing trade offer error codes to console

### ISSUE THREAD

**Issue by Danny178** [FatherFoxxy/CSharpTradeOffers#22]
Hey there

Can anyone help me? How can I output trade offer error codes (e.g. [this one](http://i.imgur.com/AaicFH1.jpg?1)) to console with example of exchanger bot? I need to output the error code if offer was not made.

Thanks in advance!

**Comment by FatherFoxxy** [comment]
Added in this commit https://github.com/FatherFoxxy/CSharpTradeOffers/commit/3f81d546df5489c9dfcfa80ac9d7be6ee5053b8a
