### ISSUE TITLE
System.ArgumentOutOfRangeException in FetchConfirmations()

### ISSUE THREAD

**Issue by WayerUniverse** [FatherFoxxy/CSharpTradeOffers#25]
Have method and in line with foreaching confirmations i have this error (System.ArgumentOutOfRangeException).

`private static void AcceptConfirmationsLoop(SteamGuardAccount sgAccount)
        {
            sgAccount.RefreshSession(); `

            while (true) //permanent loop, can be changed 

            {

                Console.WriteLine(sgAccount.GenerateSteamGuardCode());

                foreach (Confirmation confirmation in sgAccount.FetchConfirmations())

                {

                    sgAccount.AcceptConfirmation(confirmation);

                }

                Thread.Sleep(30000);

            }

        }

I'm updated old method and deleted WebLogin and _account variable, cause in SteamAuth i'm found the RefreshSession() method.

If i using old code with replace cookie`s i have some problem to.

What i need to do?

**Comment by FatherFoxxy** [comment]
Please bring this issue up on the actual SteamAuth github, I do not own that project.
