### ISSUE TITLE
problems with AcceptTradeOffer

### ISSUE THREAD

**Issue by millworm** [FatherFoxxy/CSharpTradeOffers#26]
after authorization tradeoffers are accepted normally. but if you try to take the exchange after 20-30 minutes , they will not be accepted with errors timeout or protocolerror. somehow it is possible to fix it?

**Comment by FatherFoxxy** [comment]
After 20-30 minutes of what?

**Comment by millworm** [comment]
oh. after turning on the bot
12-00 turn on the bot . 12-30 sent to the exchange , but it is impossible to take it

**Comment by FatherFoxxy** [comment]
That doesn't sound like it's my library's fault. You may have been disconnected from Steam and need to log in again in order to get a valid SessionID

**Comment by millworm** [comment]
is there any way to keep the working session , when using two factor auth?

**Comment by FatherFoxxy** [comment]
No, because Steam deauthorizes all tokens iirc.

**Comment by millworm** [comment]
hmm . interesting. the problem only occurs when run under mono

**Comment by FatherFoxxy** [comment]
Then the only advice I can give you is to not run it under Mono. I only ever tested this under .NET 4.5 and above. If you can fix it, go for it. I, however, am unable to because I am unfamiliar with Mono and its idiosyncrasies.
