### ISSUE TITLE
XML Serialize

### ISSUE THREAD

**Issue by Giswald** [FatherFoxxy/CSharpTradeOffers#3]
Can this be changed to JsonConvert.DeserializeObject instead of the XmlSerializer?

https://github.com/FatherFoxxy/CSharpTradeOffers/blob/master/CSharpTradeOffers/Community/CommunityHandler.cs#L218

**Comment by FatherFoxxy** [comment]
The API is only exposed through XML, is JsonConvert able to accomplish this?
